apiVersion: 1

datasources:
  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    access: proxy
    isDefault: true
    jsonData:
      azureAuthType: clientsecret
      cloudName: AzureCloud
      tenantId: ${AZURE_TENANT_ID}
      clientId: ${AZURE_CLIENT_ID}
      subscriptionId: ${AZURE_SUBSCRIPTION_ID}
      logAnalyticsDefaultWorkspace: ${LAW_WORKSPACE_ID}
    secureJsonData:
      clientSecret: ${AZURE_CLIENT_SECRET}
